### Create Admin
POST http://localhost:3000/auth/setup-admin
Content-Type: application/json

{
  "email": "admin@restaurant.com",
  "password": "Admin123!",
  "name": "Restaurant Admin",
  "restaurantName": "My Restaurant",
  "address": "123 kenyatta avenue, Nairobi",
  "phone": "+254712345678"
}

### Create Restaurant (Protected)
POST http://localhost:3000/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcmVzdGF1cmFudC5jb20iLCJyb2xlIjoiQURNSU4iLCJyZXN0YXVyYW50SWQiOm51bGwsImlhdCI6MTc2NDU5MzU3OCwiZXhwIjoxNzY1MTk4Mzc4fQ.WkgXLxy4SMqKsZdTPr9o-9xXmGYXD3-kCJKMRbl2Hw8
Content-Type: application/json

{
  "name": "Mama's Kitchen",
  "phone": "0712345678",
  "email": "info@restaurant.com",
  "address": "123 Main Street, Nairobi",
  "openingTime": "09:00",
  "closingTime": "22:00",
  "timezone": "Africa/Nairobi",
  "logo": "https://example.com/logo.png"
}

